### PR TITLE
CUDA benchmarks

### PR DESCRIPTION
**Pull request by jjravi**
This adds cuda transfers for NVIDIA GPUs.

### CODE REVIEW

**Comment by jeanbez** [comment]
@jjravi Could you please add the necessary documentation for this PR?

**Comment by sbyna** [comment]
@jjravi Have you tested these GPU I/O benchmarks recently? Can you please add the documentation on how to use them?

**Comment by jeanbez** [comment]
@jjravi do you have any updates on the test and documentation?

**Comment by jeanbez** [comment]
Temporarily closing this PR due to limitations.

**Pull request closed without merging**
