### PR TITLE
Include OpenPMD access pattern

### PR DESCRIPTION
**Pull request by jeanbez**
Include OpenPMD/WarpX I/O access pattern in h5bench

### CODE REVIEW

**Comment by jeanbez** [comment]
Need to wait for https://github.com/openPMD/openPMD-api/pull/1144 to be merged.

**Comment by jeanbez** [comment]
Updated documentation is available at https://h5bench.readthedocs.io/en/openpmd-support/openpmd.html

**Comment by sbyna** [comment]
for the configuration of this benchmark, what are the valid values or ranges? could be specified in the documentation or runtime checks.

**Comment by jeanbez** [comment]
@sbyna I've checked OpenPMD's code and found their checks and limits. I've updated our documentation accordingly.

**Review by sbyna — APPROVED** [review]

**Pull request merged**
